---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-dump
  name: http-dump
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-dump
  template:
    metadata:
      labels:
        app: http-dump
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8080'
        prometheus.io/app-metrics: 'true'
        prometheus.io/app-metrics-path: '/metrics'
        k8s.monitor.config.scalyr.com/scrape: 'true'
        log.config.scalyr.com/attributes.parser: accessLog
        k8s.monitor.config.scalyr.com/scrape_interval: '1'
        k8s.monitor.config.scalyr.com/attributes: '{"namespace": "http-dump", "app": "${pod_labels_app}", "image": "gmalbrand/http-dump:master-50"}'
    spec:
      containers:
      - image: gmalbrand/http-dump:latest
        name: http-dump
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-dump
  name: http-dump
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-dump
  type: LoadBalancer
