apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-dump
  namespace: http-dump
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-dump
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: Value
        averageValue: 20m
  behavior:
    scaleDown:
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
    scaleUp:
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
